import { test, expect } from '@playwright/test'

test('portfolio interactions, real work, and contact links', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page).toHaveTitle(/Nitesh Kumar/)
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Every frame.')
  await expect(page.locator('.hero-portrait img')).toHaveJSProperty('complete', true)
  await expect(page.locator('.project-card')).toHaveCount(2)
  await page.getByRole('button', { name: 'View all long form work' }).click()
  await expect(page.locator('.project-card')).toHaveCount(6)
  await page.getByRole('button', { name: 'Play A designer’s journey', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.locator('dialog iframe')).toHaveAttribute('src', /2dtas6lbR80/)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('tab', { name: /SHORT FORM VIDEOS/ }).click()
  await expect(page.locator('.short-card')).toHaveCount(4)
  await page.getByRole('button', { name: 'View all short form work' }).click()
  await expect(page.locator('.short-card')).toHaveCount(6)
  await page.getByRole('button', { name: 'Play The power of an edit', exact: true }).click()
  await expect(page.locator('.vertical-dialog')).toBeVisible()
  await expect(page.locator('dialog iframe')).toHaveAttribute('src', /7TuPSZmzOqY/)
  await page.getByRole('button', { name: 'Close video', exact: true }).click()
  await page.getByRole('tab', { name: 'Sound', exact: true }).click()
  await expect(page.locator('#dna-description')).toContainText('Give every frame a voice')
  await page.getByRole('tab', { name: /03 Polish/ }).click()
  await expect(page.locator('#process-panel')).toContainText('Polish the details.')
  await expect(page.locator('.contact-links a').nth(0)).toHaveAttribute('href', 'https://wa.me/919315841623')
  await expect(page.locator('.contact-links a').nth(1)).toHaveAttribute('href', 'mailto:niteshedits2002@gmail.com')
  await expect(page.locator('.contact-links a').nth(2)).toHaveAttribute('href', 'https://www.instagram.com/framesbynitesh/')
  expect(errors).toEqual([])
})

test('mobile navigation and overflow', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.locator('body')).toBeVisible()
  await page.getByRole('button', { name: 'Open navigation' }).click()
  await expect(page.locator('.main-nav')).toBeVisible()
  await page.getByRole('link', { name: 'Work', exact: true }).click()
  await expect(page.locator('.main-nav')).not.toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('tab', { name: /SHORT FORM VIDEOS/ }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('unconfigured studio does not allow fake login or edits', async ({ page }) => {
  await page.goto('/admin')
  await expect(page.getByText('DATABASE CONNECTION REQUIRED')).toBeVisible()
  await expect(page.getByRole('link', { name: /Read the complete setup guide/ })).toHaveAttribute('href', '/SETUP.md')
  await expect(page.locator('input[type=password]')).toHaveCount(0)
  await expect(page.getByText('No admin account or password has been made public.', { exact: false })).toBeVisible()
})
